spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false
    username: demo_user
    password: demo_pass
# for H2
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    initialization-mode: embedded
#    continue-on-error: false
#    platform: h2
#    sql-script-encoding: UTF-8
#    schema:
#      - classpath:/scripts/
#      - classpath:/scripts/schema-h2.sql
#      - classpath:/scripts/schema-mysql.sql
#    data:
#      - classpath:/scripts/
#      - classpath:/scripts/data-h2.sql
#      - classpath:/scripts/data-mysql.sql
    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/demo_db?useSSL=false
#      username: demo_user
#      password: demo_pass
#      driver-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 4
      minimum-idle: 4
      connection-test-query: select 1
      connection-timeout: 30000
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
  h2:
    console:
      enabled: true
      path: /h2-console
  devtools:
    restart:
      enabled: true
      log-condition-evaluation-delta: true

# EMBEDDED SERVER CONFIGURATION
server:
  servlet:
    context-path: /app
  port: 9000

logging.file: demo.log
logging:
  file:
    max-size: 50MB
    max-history: 10
  level:
    root: info
    org.springframework: info
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.example.demo: debug
