 create table memo (
   id bigint generated by default as identity,
   description varchar(255) not null,
   done boolean not null,
   title varchar(255) not null,
   updated timestamp not null,
   primary key (id)
);
